### PR TITLE
Read ELF SONAMEs directly from process memory when possible.

### LINKED ISSUE #79: Support libraries mapped from within APKs on Android
We've started encountering minidumps coming from Android builds of Firefox where the shared libraries have been mapped directly from an APK (which is just a ZIP file, so they're probably stored uncompressed). The relevant mappings look like this:
```
7e042700c000-7e042700e000 r--p 00001000 fd:20 7315                       /data/app/org.mozilla.geckoview.test_runner-1/split_config.x86_64.apk
7e042700f000-7e042707e000 r-xp 00002000 fd:20 7315                       /data/app/org.mozilla.geckoview.test_runner-1/split_config.x86_64.apk
7e042707e000-7e04270af000 r--p 00071000 fd:20 7315                       /data/app/org.mozilla.geckoview.test_runner-1/split_config.x86_64.apk
7e04270b0000-7e04270b2000 r--p 000a2000 fd:20 7315                       /data/app/org.mozilla.geckoview.test_runner-1/split_config.x86_64.apk
7e04270b2000-7e04270b3000 rw-p 000a4000 fd:20 7315                       /data/app/org.mozilla.geckoview.test_runner-1/split_config.x86_64.apk
```
Since we record the module name we find in the mappings the minidumps are unusable, as we can't symbolicate them.

We look for the SONAME in the mapped [ELF file](https://github.com/rust-minidump/minidump-writer/blob/a73769022d585ecf42c7cec17039d71b923b39ad/src/linux/maps_reader.rs#L286) so we should be finding it, but chances are that we are failing to open the underlying file [here](https://github.com/rust-minidump/minidump-writer/blob/a73769022d585ecf42c7cec17039d71b923b39ad/src/linux/maps_reader.rs#L267).

So this could be related to issue https://github.com/rust-minidump/minidump-writer/issues/71, because we'd be certainly capable of finding the SONAME within the crashed process' memory. If we switch reading the build ID from there, reading the SONAME would be a trivial addition.

### PR DESCRIPTION
**Pull request by afranchuk**
When this fails, it falls back to the previous behavior of trying to open the mapped file name directly.

Closes #79.

### CODE REVIEW

**Comment by afranchuk** [comment]
I'll update the ELF fixture to add an SONAME to test this.

**Review by Jake-Shadle — APPROVED** [review]

**Comment by gabrielesvelto** [comment]
Sorry my review is taking a bit but I'm doing some testing directly in Firefox and this seems to work only for external libraries, not our own ones, so I'm trying to figure out what's wrong (or if it's something specific to my box).

File: src/linux/module_reader.rs [hunk 1]
```diff
@@ -0,0 +1,433 @@
...
+        let context = Ctx::new(header.container()?, header.endianness()?);
+        Ok(ModuleReader {
+            module_memory,
+            header,
+            context,
+        })
+    }
+
+    pub fn soname(&self) -> Result<String, Error> {
+        let section_headers = self.read_section_headers()?;
```
Comment (gabrielesvelto) [inline src/linux/module_reader.rs:162]: For some reason this call is always failing when encountering our executables in Firefox, even though it works fine for system libraries. Could you check with one of our builds and see what's going on?

Note that I tried this with an elf-hack build because that's what we ship.

**Review by gabrielesvelto — CHANGES_REQUESTED** [review]

File: src/linux/module_reader.rs (hunk 1 above)
Comment (afranchuk) [reply src/linux/module_reader.rs:162]: Interesting, I'll try it out!

Comment (afranchuk) [reply src/linux/module_reader.rs:162]: I'm unable to reproduce this, both with firefox release and nightly (as downloaded directly from our website). Is there something else I need to do? Can you tell me exactly what you did to test? I added a test like
```rust
    #[test]
    fn soname_firefox() {
        let bytes = include_bytes!("/home/afranchuk/Downloads/125/firefox/libxul.so");
        let reader = ModuleReader::new(&bytes[..]).unwrap();
        let soname = reader.soname().unwrap();
        assert_eq!(soname, "libxul.so");
    }
```

I tried with a few other libraries too.

Comment (gabrielesvelto) [reply src/linux/module_reader.rs:162]: I patched the gecko sources to build minidump-writer with this PR included and crashed a child process to check how the code would behave in the wild.

Comment (afranchuk) [reply src/linux/module_reader.rs:162]: Perhaps this is a vaddr vs file offset issue. I'll try that.

**Comment by afranchuk** [comment]
Not all binaries have the section header table present when loaded in memory. However the program headers will be there, so I added another path which is preferred and uses only the program headers and the dynamic section information. This seems to work with all shared objects loaded by firefox at runtime when I tested it. We _might_ still want a fallback of trying to load directly from the file (if present) if reading from memory fails for some reason.

**Comment by afranchuk** [comment]
I'm not sure why the android test is failing...

File: .cargo/config.toml [hunk 2]
```diff
@@ -11,4 +11,6 @@
 # ]
 [target.x86_64-linux-android]
 linker = "x86_64-linux-android30-clang"
+# By default the linker _doesn't_ generate a build-id, however we want one for our tests.
+rustflags = ["-C", "link-args=-Wl,--build-id=sha1"]
```
Comment (gabrielesvelto) [inline .cargo/config.toml:15]: Nice catch!

**Comment by afranchuk** [comment]
This is probably ready to merge.

**Review by gabrielesvelto — APPROVED** [review]
Indeed, LGTM
