### PR TITLE
Write stacks correctly during stack overflows

### LINKED ISSUE #24: Detect guard pages and dump the real stack instead when encountering stack overflows on Linux
After landing bug [1678152](https://bugzilla.mozilla.org/show_bug.cgi?id=1678152) in Firefox we noticed that several of the crash reports we got had an empty stack. The first frame was fine but the rest of the stack appeared to be an empty 4KiB chunk. As it turns out in those crashes the stack pointer had been bumped straight into the guard page below the stack causing [this code](https://searchfox.org/mozilla-central/rev/88792eff309001778cb2431f2a0ed92f8f3c258a/toolkit/crashreporter/breakpad-client/linux/minidump_writer/linux_dumper.cc#791-795) code to mistake the guard page for the stack and dumping it. The new writer [inherited this flaw from Breakpad](https://github.com/rust-minidump/minidump-writer/blob/39a1c8009dd59c4c43d381f6b2a24fa6ae048ef6/src/linux/ptrace_dumper.rs#L320-L325). To fix this we should have `MappingInfo` store the readable/writable flags in addition to the executable one and if the mapping [we find here](https://github.com/rust-minidump/minidump-writer/blob/39a1c8009dd59c4c43d381f6b2a24fa6ae048ef6/src/linux/ptrace_dumper.rs#L330-L332) is non readable/writable then we should shift the stack pointer to the previous page and pick the previous mapping instead.

### PR DESCRIPTION
**Pull request by gabrielesvelto**
When encountering a stack overflow we often crash accessing the guard page. The logic assumed that wherever the stack pointer was so was the stack, but this lead the writer to dump the guard page in these cases. This patch changes the logic to inspect the properties of the mapping that appears to correspond to the stack and - if it looks like a guard page - look for the actual stack instead.

This fixes #24

### CODE REVIEW

**Comment by gabrielesvelto** [comment]
This is a WIP, I need to test it in real world scenarios and add tests too.

**Comment by gabrielesvelto** [comment]
This is as good as it gets, I tried to match the original intent, removing the redundant limit on the amount of stack we captured while ensuring we always grab a stack, provided the overflow is within 1MiB of where it should be as that's the size of guard pages in Linux ATM.

**Comment by gabrielesvelto** [comment]
@Jake-Shadle would you have time to take a look?

**Comment by Jake-Shadle** [comment]
Oh sorry, this completely fell off my radar, will review tomorrow!

**Comment by gabrielesvelto** [comment]
Thanks!

File: src/linux/maps_reader.rs [hunk 1]
```diff
@@ -339,6 +337,18 @@ impl MappingInfo {
...
+    }
+
+    pub fn is_readable(&self) -> bool {
+        self.permissions.contains(MMPermissions::READ)
+    }
+
+    pub fn is_writable(&self) -> bool {
+        self.permissions.contains(MMPermissions::WRITE)
+    }
 }
```
Comment (Jake-Shadle) [inline src/linux/maps_reader.rs:352]: These could be inline, but that's just a nit.

**Review by Jake-Shadle — APPROVED** [review]
LGTM, can cut a release on Monday unless there is a rush.

**Comment by gabrielesvelto** [comment]
> LGTM, can cut a release on Monday unless there is a rush.

No rush at all.
